spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=${DDL_AUTO:validate}
spring.jpa.show-sql=false

spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${AZURE_JWKS_URI:}
spring.security.oauth2.resourceserver.jwt.issuer-uri=${AZURE_ISSUER_URI}